// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyyYBrhZ2FvV1lLYGcwCvNN5FwWgELRY',
    appId: '1:500843951722:web:6b11f646a7298302a03c13',
    messagingSenderId: '500843951722',
    projectId: 'zalusomart',
    authDomain: 'zalusomart.firebaseapp.com',
    storageBucket: 'zalusomart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaUSx40PmJu0R0hYocfWozD19p0IwXT0A',
    appId: '1:500843951722:android:14fe2227979bee06a03c13',
    messagingSenderId: '500843951722',
    projectId: 'zalusomart',
    storageBucket: 'zalusomart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0adePrzQo3varGcSOQtn2FjsShXDiXtw',
    appId: '1:500843951722:ios:80e8b34e541ea01da03c13',
    messagingSenderId: '500843951722',
    projectId: 'zalusomart',
    storageBucket: 'zalusomart.appspot.com',
    iosBundleId: 'com.example.zalusomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0adePrzQo3varGcSOQtn2FjsShXDiXtw',
    appId: '1:500843951722:ios:80e8b34e541ea01da03c13',
    messagingSenderId: '500843951722',
    projectId: 'zalusomart',
    storageBucket: 'zalusomart.appspot.com',
    iosBundleId: 'com.example.zalusomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoyyYBrhZ2FvV1lLYGcwCvNN5FwWgELRY',
    appId: '1:500843951722:web:ac2ca67b49719e3fa03c13',
    messagingSenderId: '500843951722',
    projectId: 'zalusomart',
    authDomain: 'zalusomart.firebaseapp.com',
    storageBucket: 'zalusomart.appspot.com',
  );
}
